### ISSUE TITLE
Question: minimum_isoform_percent

### ISSUE THREAD

**Issue by martynakgajos** [nanoporetech/pinfish#11]
What is the minimum isoform percentage parameter? And what does the value 1 mean: 1 as 1.0 (so 100%) or 1 as 1%?

**Comment by bsipos** [comment]
It's a percent, so it is 1%.

**Comment by martynakgajos** [comment]
And what does this parameter mean? What is it responsible for?

**Comment by bsipos** [comment]
It filters out isoforms with less that this percent of coverage at a "locus" (a group of transcripts starting roughly at the same position). Safe to set it to zero if worried about confusing your results.

**Comment by defendant602** [comment]
@bsipos 
Could you please provide a recommended value for this parameter when annotating a genome using ONT cDNA data? 

Thanks!
