### ISSUE TITLE
Scaffolding using long-read RNA?

### ISSUE THREAD

**Issue by andreaswallberg** [nanoporetech/pinfish#14]
Dear developers,

Any chance that this tool could be co-opted or extended to provide information about contig adjacency and scaffolding from split long-read RNA mappings?

Cheers!

**Comment by bsipos** [comment]
Since this tool depends on spliced alignments I don't think it is a good starting point for scaffolding. However one could map the reads to the scaffolds using minimap2 -ax map-ont and then parse the output looking for reads having secondary alignments on different contigs.

Cheers,
Botond
