### ISSUE TITLE
Using medaka with transcriptome data

### ISSUE THREAD

**Issue by MartinTes** [nanoporetech/pinfish#15]
Hi,

I am new with Pomoxis and I am trying to run a polishing step on budgerigar transcriptomic data after genome reference-based assembly but I am getting an error in the step of generating consensus.

First, I a successfully created reference-based assembly (with the budgerigar genome but only with the longest transcript per gene selected) with the following script:

#!/bin/bash
NPROC=$(nproc)
BASECALLS=data/Pool4_merged_trimmed_BC.fastq
REFERENCE=/home/martin.tesicky/Medaka_parrots/Pool4/medaka_walkthrough/Budgerigar_genome_longest_transcript_mart_export.fasta
mini_assemble -i ${BASECALLS} -r ${REFERENCE} -o draft_assm_with_reference -p assm -t ${NPROC}

Then, I run a Polishing a Consensus as follows:

#!/bin/bash
NPROC=$(nproc)
BASECALLS=data/Pool4_merged_trimmed_BC.fastq
DRAFT=draft_assm_with_reference/assm_final.fa
OUTDIR=medaka_consensus_with_reference_1_12
medaka_consensus -i ${BASECALLS} -d ${DRAFT} -o ${OUTDIR} -t ${NPROC} -m r941_min_h
 
When I am doing the medaka consensus step the fasta file with the consensus sequence is always empty and I am getting calls from logfile: "Failed to stitch consensus chunks." and from a terminal (please, see below and see also complete output in attached files).  I also tried to use de-novo assembly without using reference but I got a very low number of contigs (only ca 1500) and polishing step was working with this attitude.  When I using reference-based assembly I have many more contigs (ca 12 000), but the consensus step is not working. I would also welcome any piece of advice on which parameters should I adjust for de-novo assembly since we have also other species where the genomes are not available @cjw85. 

I would be very grateful for any help. 

 [file):]([url](url
[typescript.txt](https://github.com/nanoporetech/pomoxis/files/3910297/typescript.txt)
[medaka_consenus_runner_with_reference__01_12_logfile.txt](https://github.com/nanoporetech/pomoxis/files/3910302/medaka_consenus_runner_with_reference__01_12_logfile.txt)

))

Traceback (most recent call last):
  File "/home/martin.tesicky/miniconda3/envs/medaka/bin/medaka", line 11, in <module>
    sys.exit(main())
  File "/home/martin.tesicky/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/medaka.py", line 431, in main
    args.func(args)
  File "/home/martin.tesicky/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 137, in stitch
    for contigs in executor.map(worker, regions):
  File "/home/martin.tesicky/miniconda3/envs/medaka/lib/python3.6/concurrent/futures/process.py", line 496, in map
    timeout=timeout)
  File "/home/martin.tesicky/miniconda3/envs/medaka/lib/python3.6/concurrent/futures/_base.py", line 575, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/home/martin.tesicky/miniconda3/envs/medaka/lib/python3.6/concurrent/futures/_base.py", line 575, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
  File "/home/martin.tesicky/miniconda3/envs/medaka/lib/python3.6/concurrent/futures/process.py", line 139, in _get_chunks
    chunk = tuple(itertools.islice(it, chunksize))
  File "/home/martin.tesicky/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/common.py", line 610, in grouper
    batch.append(next(gen))
  File "/home/martin.tesicky/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/stitch.py", line 130, in <genexpr>
    (common.Region.from_string(r) for r in args.regions),
  File "/home/martin.tesicky/miniconda3/envs/medaka/lib/python3.6/site-packages/medaka/common.py", line 469, in from_string
    start = int(bounds)
ValueError: invalid literal for int() with base 10: 'ubiquinone'
(medaka) martin.tesicky@turbacz:~/Medaka_parrots/Pool4/medaka_walkthrough$ 
(medaka) martin.tesicky@turbacz:~/Medaka_parrots/Pool4/medaka_walkthrough$ ls
[0m[01;32massess_assembly_runner.bash[0m
[01;32massess_assembly_stats_runner.bash[0m

**Comment by MartinTes** [comment]
Hi @bsipos,
thank you very much for your suggestion.  We will definitively try to explore more pinfish pipeline and I will let you know about the results. I think that birds have quite good synteny in their genomes and using reference-based assembly could work also for other species where we don´t have their genomes.  

I noticed that both Pomoxis pipeline and Pinfish employe Racon for polishing sequences and I have a question if I need to have for this polishing step a reference genome? If I use Pinfish pipeline for species with the genome of other closely related species cannot I implement any other errors to our data during polishing? I apologize for this question but I am actually not sure how Racon works within this pipelines,

Thank you very much.

**Comment by MartinTes** [comment]
Hi @ksahlin,
thank you very much much. When I looked closely at my data for reference-based assembly for budgerigar that processed by Pomoxis (default model for Medaka polishing)  it turned up that some immune genes not only with low coverage but also with higher coverage had even worsen quality of reads after polishing than before which is quite unexpected... and I will have to definitively explore more possibilities.

If understood well, I could try to do de-novo transcriptome-clustering using isONclust, then convert the output clusters to fasta files, employ spoa to make consensual sequences and then try to independently use Medaka for polishing with some pre-steps in Racon?

Many thanks in advance.

**Comment by ksahlin** [comment]
Hi @MartinTes,

I don't know how you polish transcript reads, but if you used any tool designed for genomic sequences, low quality it is expected because of exon (and other differences). You will likely get chimeric reads.

As for clustering the reads, isONclust should do a decent job. However, for the downstream  "polishing" steps. Keep in mind the (significant) caveats listed in my previous message. That is, polishing the augmented (possibly incomplete) gene-consensus constructed by spoa with transcriptomic reads coming from different isoforms. That does not sound promising and I would guess it is prone to errors.

**Comment by MartinTes** [comment]
Hi @ksahlin,
yes, that is a good point with polishing. Could it be a way to partially overcome this issue if we preselect raw reads by mapping them to the longest transcript per gene from the genome and then to take only these reads as an input?

**Comment by bsipos** [comment]
@MartinTes @ksahlin If you use pinfish for clustering then there should be no exon differences between the reads which are polished together. Moreover, since the reference is only used during clustering, the consensuses will represent the actual species.
When using pinfish, preselecting reads is not necessary and one would obtain polished transcripts for all and not just the longest isoform.

**Comment by ksahlin** [comment]
Yes indeed, for any kind of reference-based analysis, go with pinfish. My comments are only in regards to a genome-reference free analysis.

**Comment by MartinTes** [comment]
@ksahlin @bsipos OK, thank you very much for your pieces of advice. I going to run pinfish and hope to have some results soon.
