### ISSUE TITLE
polish_clusters error?

### ISSUE THREAD

**Issue by Renxiaoliang** [nanoporetech/pinfish#16]
Hi,  I am using "pipeline pinfish analysis" to annotate genome with ONT cDNA long reads. However, when it came to "polish_clusters" step, I got the error message like the following: 

polish_clusters: 15:11:47 Failed running command: samtools view -h - exit status 1

[Wed Dec 18 15:11:47 2019]

Error in rule polish_clusters:

    jobid: 7

    output: results/polished_transcripts.fas

    conda-env: /home/work/rxl_wkdir/wkdir_N06/pipeline-pinfish-analysis/.snakemake/conda/bfe8fba3

    shell:        

    /home/work/rxl_wkdir/wkdir_N06/pipeline-pinfish-analysis/pinfish/polish_clusters/polish_clusters -t 30 -a results/cluster_memberships.tsv -c 10 -o results/polished_transcripts.fas alignments/reads_aln_sorted.bam    

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.

I do install minimap2, samtools, and racon as dependencies, but I don't know how did this error happen. Could anybody give some advices on this? Thank you very much!

**Comment by bsipos** [comment]
Did you install samtools through a package manager? If yes, it is likely that it is too old.
Please install mininconda and run the snakemake pipeline with `--use-conda`.
Best,
Botond

**Comment by huangl07** [comment]
well I get the same error when I use samtools 1.10

**Comment by bsipos** [comment]
Well, the only explanation is that you don't have samtools in your path. If you use conda to manage dependencies this should not happen.

**Comment by huangl07** [comment]
Well,bsipos,

I don't think so,course I could do  `which samtools` and get samtools path

so I think maybe there is another answer

Maybe conda is necessary？

**Comment by bsipos** [comment]
Yeah, it seems your issue is not with samtools. Coult you please look at the files left in temp after the crash. It seems there was a problem with aligning the reads.

**Comment by MartinTes** [comment]
I have just got the same error both with my data and training data with Samtools version 1.19

**Comment by huangl07** [comment]
Hi bsipos

I use make test_sim， but I got the error

`$make test_sim
./polish_clusters -t 40 -c 100 -o test_data/cons.fas -a test_data/cls_sirv_sim_mm2.tab ../spliced_bam2gff/test_data/sirv_simulated.bam
polish_clusters: 08:39:57 Failed running command: samtools view -h - exit status 1
make: *** [Makefile:45: test_sim] Error 1
`
I think maybe there are something wrong in your code

**Comment by huangl07** [comment]
I could use samtools index to get the idx for bam and
the header is
`@HD	VN:1.6	SO:coordinate
@PG	ID:minimap2	PN:minimap2	VN:2.17-r954-dirty	CL:minimap2 -t 8 -ax splice --split-prefix -uf new_ref.fa /mnt/ilustre/centos7users/zhenyu.lu/Schoolar/Nanopore/data/mouse_data/cDNA/submitted_data/pychopper/trimmed_BYK_CNB_ONT_1_FAH67243_A.fastq.full_length_output.fq
@PG	ID:samtools	PN:samtools	PP:minimap2	VN:1.10	CL:samtools view -q 10 -F 2304 -Sb -
@PG	ID:samtools.1	PN:samtools	PP:samtools	VN:1.10	CL:samtools sort -@ 8 -o out.bam -
@PG	ID:samtools.2	PN:samtools	PP:samtools.1	VN:1.10	CL:samtools view -H out.bam
@SQ	SN:1	LN:195471971
@SQ	SN:2	LN:182113224
@SQ	SN:3	LN:160039680
@SQ	SN:4	LN:156508116
@SQ	SN:5	LN:151834684
@SQ	SN:6	LN:149736546
@SQ	SN:7	LN:145441459
@SQ	SN:8	LN:129401213
@SQ	SN:9	LN:124595110
@SQ	SN:10	LN:130694993
@SQ	SN:11	LN:122082543
@SQ	SN:12	LN:120129022
@SQ	SN:13	LN:120421639
@SQ	SN:14	LN:124902244
@SQ	SN:15	LN:104043685
@SQ	SN:16	LN:98207768
@SQ	SN:17	LN:94987271
@SQ	SN:18	LN:90702639
@SQ	SN:19	LN:61431566
@SQ	SN:X	LN:171031299
@SQ	SN:Y	LN:91744698
@SQ	SN:MT	LN:16299
@SQ	SN:CHR_MG171_PATCH	LN:151834685
@SQ	SN:CHR_MG4222_MG3908_PATCH	LN:94987243
@SQ	SN:CHR_MG51_PATCH	LN:156507375
@SQ	SN:CHR_MG3496_PATCH	LN:195440828
@SQ	SN:CHR_MG4200_PATCH	LN:94983374
@SQ	SN:CHR_MG4243_PATCH	LN:156484188
@SQ	SN:CHR_MG4209_PATCH	LN:91793962
@SQ	SN:CHR_MG74_PATCH	LN:104052134
@SQ	SN:CHR_MG4310_MG4311_PATCH	LN:156656003
@SQ	SN:CHR_MG4249_PATCH	LN:61433356
@SQ	SN:CHR_MG3833_MG4220_PATCH	LN:98208654
@SQ	SN:CHR_MG3231_PATCH	LN:171029545
@SQ	SN:CHR_MG4151_PATCH	LN:145439975
@SQ	SN:CHR_MG104_PATCH	LN:170913546
@SQ	SN:CHR_MMCHR1_CHORI29_IDD5_1	LN:195506435
@SQ	SN:CHR_MG3700_PATCH	LN:90658154
@SQ	SN:CHR_MG3530_PATCH	LN:130695022
@SQ	SN:CHR_MG4261_PATCH	LN:103906836
@SQ	SN:CHR_MG3251_PATCH	LN:145419646
@SQ	SN:CHR_MG3562_PATCH	LN:156470354
@SQ	SN:CHR_CAST_EI_MMCHR11_CTG4	LN:122190308
@SQ	SN:CHR_WSB_EIJ_MMCHR11_CTG2	LN:122242168
@SQ	SN:CHR_PWK_PHJ_MMCHR11_CTG2	LN:122246885
@SQ	SN:CHR_MG3648_PATCH	LN:104165524
@SQ	SN:CHR_MG3618_PATCH	LN:156477076
@SQ	SN:CHR_CAST_EI_MMCHR11_CTG5	LN:122035401
@SQ	SN:CHR_PWK_PHJ_MMCHR11_CTG3	LN:122032376
@SQ	SN:CHR_MG4136_PATCH	LN:156508116
@SQ	SN:CHR_MG4138_PATCH	LN:130620757
@SQ	SN:CHR_MG3835_PATCH	LN:90835696
@SQ	SN:CHR_MG89_PATCH	LN:159939961
@SQ	SN:CHR_MG4213_PATCH	LN:91736668
@SQ	SN:CHR_MG3829_PATCH	LN:122082543
@SQ	SN:CHR_MG209_PATCH	LN:94987270
@SQ	SN:CHR_WSB_EIJ_MMCHR11_CTG3	LN:122041104
@SQ	SN:CHR_MG4308_PATCH	LN:122082543
@SQ	SN:CHR_MG3609_PATCH	LN:156568640
@SQ	SN:CHR_MG4180_PATCH	LN:120129530
@SQ	SN:CHR_MG3686_PATCH	LN:170897390
@SQ	SN:CHR_MG65_PATCH	LN:61442615
@SQ	SN:CHR_MG3627_PATCH	LN:124903046
@SQ	SN:CHR_MG3999_PATCH	LN:195424274
@SQ	SN:CHR_MG3699_PATCH	LN:90657263
@SQ	SN:CHR_MG4254_PATCH	LN:171079788
@SQ	SN:CHR_MG4198_PATCH	LN:94938704
@SQ	SN:CHR_MG153_PATCH	LN:61431565
@SQ	SN:CHR_MG3656_PATCH	LN:170985484
@SQ	SN:CHR_MG4211_PATCH	LN:91797447
@SQ	SN:CHR_MG4255_PATCH	LN:171051513
@SQ	SN:CHR_WSB_EIJ_MMCHR11_CTG1	LN:122025577
@SQ	SN:CHR_MG4248_PATCH	LN:160065929
@SQ	SN:CHR_MG4288_PATCH	LN:104043690
@SQ	SN:CHR_MG132_PATCH	LN:124595140
@SQ	SN:CHR_MG4212_PATCH	LN:151862668
@SQ	SN:CHR_MG4214_PATCH	LN:170938523
@SQ	SN:CHR_MG4281_PATCH	LN:195471970
@SQ	SN:CHR_MG191_PATCH	LN:182113225
@SQ	SN:CHR_MG4266_PATCH	LN:156460002
@SQ	SN:CHR_PWK_PHJ_MMCHR11_CTG1	LN:121996417
@SQ	SN:CHR_MG3561_PATCH	LN:156464115
@SQ	SN:CHR_MG190_MG3751_PATCH	LN:129401208
@SQ	SN:CHR_MG3712_PATCH	LN:159992652
@SQ	SN:CHR_MG3836_PATCH	LN:182124663
@SQ	SN:CHR_MG4259_PATCH	LN:104073167
@SQ	SN:CHR_MG3683_PATCH	LN:170944389
@SQ	SN:CHR_MG184_PATCH	LN:149736545
@SQ	SN:CHR_MG4264_PATCH	LN:130719490
@SQ	SN:CHR_MG117_PATCH	LN:124546979
@SQ	SN:CHR_MG3714_PATCH	LN:159951792
@SQ	SN:CHR_MG3490_PATCH	LN:120126208
@SQ	SN:CHR_MG3172_PATCH	LN:145409378
@SQ	SN:CHR_MG4162_PATCH	LN:124852600
@SQ	SN:CHR_MG4265_PATCH	LN:156510038
@SQ	SN:JH584299_1	LN:953012
@SQ	SN:GL456233_1	LN:336933
@SQ	SN:JH584301_1	LN:259875
@SQ	SN:GL456211_1	LN:241735
@SQ	SN:GL456350_1	LN:227966
@SQ	SN:JH584293_1	LN:207968
@SQ	SN:GL456221_1	LN:206961
@SQ	SN:JH584297_1	LN:205776
@SQ	SN:JH584296_1	LN:199368
@SQ	SN:GL456354_1	LN:195993
@SQ	SN:JH584294_1	LN:191905
@SQ	SN:JH584298_1	LN:184189
@SQ	SN:JH584300_1	LN:182347
@SQ	SN:GL456219_1	LN:175968
@SQ	SN:GL456210_1	LN:169725
@SQ	SN:JH584303_1	LN:158099
@SQ	SN:JH584302_1	LN:155838
@SQ	SN:GL456212_1	LN:153618
@SQ	SN:JH584304_1	LN:114452
@SQ	SN:GL456379_1	LN:72385
@SQ	SN:GL456216_1	LN:66673
@SQ	SN:GL456393_1	LN:55711
@SQ	SN:GL456366_1	LN:47073
@SQ	SN:GL456367_1	LN:42057
@SQ	SN:GL456239_1	LN:40056
@SQ	SN:GL456213_1	LN:39340
@SQ	SN:GL456383_1	LN:38659
@SQ	SN:GL456385_1	LN:35240
@SQ	SN:GL456360_1	LN:31704
@SQ	SN:GL456378_1	LN:31602
@SQ	SN:GL456389_1	LN:28772
@SQ	SN:GL456372_1	LN:28664
@SQ	SN:GL456370_1	LN:26764
@SQ	SN:GL456381_1	LN:25871
@SQ	SN:GL456387_1	LN:24685
@SQ	SN:GL456390_1	LN:24668
@SQ	SN:GL456394_1	LN:24323
@SQ	SN:GL456392_1	LN:23629
@SQ	SN:GL456382_1	LN:23158
@SQ	SN:GL456359_1	LN:22974
@SQ	SN:GL456396_1	LN:21240
@SQ	SN:GL456368_1	LN:20208
@SQ	SN:JH584292_1	LN:14945
@SQ	SN:JH584295_1	LN:1976
`

**Comment by huangl07** [comment]
Hi bsipos

I think I found Why the errors couse when you test in utils.go `samtools view -h`

it run status is 1

when I change the utils.go to this:
`func BashExec(command string) {

    cmd := exec.Command("bash", "-c", command)
    err := cmd.Run()
    if strings.Contains(command, "samtools"){
        fmt.Println(err)
        fmt.Println("hello world")
    }
    if err != nil {
        L.Fatalf("Failed running command: %s - %s\n", command, err)
    }

}
`

it run out
`./polish_clusters -t 40 -c 100 -o test_data/cons.fas -a test_data/cls_sirv_sim_mm2.tab ../spliced_bam2gff/test_data/sirv_simulated.bam
exit status 1
hello world
polish_clusters: 09:22:09 Failed running command: samtools view -h - exit status 1`

**Comment by huangl07** [comment]
I change `samtools view -h` 2 `samtools view ` in check_dep.go and the error is gone！

**Comment by huangl07** [comment]
Hi bsipos，I change the check command ”samtools view -h“ 2  "which samtools" in line 32 at file "check_deps.go "

and then the error is gone!

**Comment by Renxiaoliang** [comment]
Hi, huangl07, I did the modification as you mentioned and it did work with no error! I don't know the rationales underlying this but thank you very much!

**Comment by Renxiaoliang** [comment]
And also, I came to the same question in the ont_tutorial_pinfish pipeline, https://github.com/nanoporetech/ont_tutorial_pinfish

I degrade samtools from 1.10 to 1.9 through conda without changing any code, and the error is gone!

**Comment by bsipos** [comment]
Interesting, it seems something changed in samtools. Will look into this and pin the version if necessary.

**Comment by Renxiaoliang** [comment]
Hi  bsipos, by the way, pychopper analysis step is not included in pipeline-pinfish-analysis, right? But for ONT cDNA reads, pychopper step is still recommonded before pipeline-pinfish-analysis? 

I noticed that ont_tutorial_pinfish pipeline contains pychopper, so I am wondering what is the difference between pipeline-pinfish-analysis and ont_tutorial_pinfish. Which one should I choose? as it seems that ont_tutorial_pinfish shows more recent updates.

Thank you very much!

**Comment by bsipos** [comment]
Yes, pychopper is not included in the pipeline and you should do it manually for cDNA. The reason is that this pipeline meant to work on cDNA and direct RNA as well.
