### ISSUE TITLE
question on cluster_gff

### ISSUE THREAD

**Issue by ljw90607** [nanoporetech/pinfish#17]
Dear @bsipos

Hello while I was doing the analysis, I ran into some question on the cluster_gff step. 
Would the cluster_gff step consider to print out the 2 different stranded cluster reads seperately as output when they happened to have matching boundary?

Thank you for your wonderful help.

Jungwoo.

**Comment by bsipos** [comment]
Dear Jungwoo,

Yes, the current version of cluster_gff would do exactly that.

Botond
