### ISSUE TITLE
error for polish cluster

### ISSUE THREAD

**Issue by MartinTes** [nanoporetech/pinfish#18]
Hi @bsipos and @ksahlin,

I am running polish_cluster with my own data (spliced_bam2gff and cluster_gff worked fine):
and I am getting the following error which has something to do with the wrong input format for racon. Besides commands, I am also including pieces of input/ output files. I already tried to ask here with a similar topic: https://github.com/nanoporetech/pinfish/issues/5  but I am not sure whether you receive any notifications when the issue is closed.

Splice bam2gf
spliced_bam2gff -M Pool4_merged_trimmed_BC.bam -t 24 > Pool4_merged_trimmed_BC_raw_transcripts.gff

cluster_gff
cluster_gff -t 24 -a Pool4_merged_trimmed_BC_raw_transcripts_clusters.tsv Pool4_merged_trimmed_BC_raw_transcripts.gff > Pool4_merged_trimmed_BC_raw_transcripts_clustered_transcripts.gff

My command polish_clusters line:
(pinfish) martin.tesicky@turbacz:~/Medaka_parrots/Pool4/pinfish$ polish_clusters -a Pool4_merged_trimmed_BC_raw_transcripts_clusters.tsv -c 50 -o Pool4_merged_t_rimmed_BCconsensus_transcripts.fas -t 24 Pool4_merged_trimmed_BC.bam
polish_clusters: 15:55:52 Polishing cluster 02e3c0c0-b1b5-4f5f-8bf5-05f83f97fbd3 of size 330
polish_clusters: 15:55:53 Polishing cluster c7a0033e-8bd3-4ea8-8539-8cfe406f915f of size 85
polish_clusters: 15:55:53 Polishing cluster e3b5ea34-f86a-42d8-9e2d-9c86a8d29b5c of size 53
polish_clusters: 15:55:54 Polishing cluster 8f8b2b1d-54d3-4b18-8dc5-3fc9b7eef4f9 of size 96
polish_clusters: 15:55:54 Polishing cluster f786d9ec-ecc0-4b5f-8862-2b4d1b72a8e1 of size 26109
polish_clusters: 15:59:42 Polishing cluster bb6413a0-83dd-452f-8e70-94e848c88720 of size 99
polish_clusters: 15:59:42 Polishing cluster 8db24705-3c4c-4e5a-b8bd-300688ff0bdc of size 50
polish_clusters: 15:59:43 Polishing cluster d28805d8-6cae-42fe-8138-a0d64a998608 of size 1345
polish_clusters: 15:59:50 Polishing cluster 46a7098b-2dd1-4f1b-966e-869613dfa32b of size 53
polish_clusters: 15:59:50 Polishing cluster 34c16ef3-891f-47aa-8946-32b963fb6812 of size 58
polish_clusters: 15:59:50 Polishing cluster d49642c2-0fd4-4c0c-8319-59d1863f57f8 of size 70
polish_clusters: 15:59:50 Polishing cluster 441903e3-5769-43cf-8043-bfb1df57c90e of size 2829
polish_clusters: 16:00:04 Polishing cluster 971c2378-3d77-43de-89ee-fd6c28e1947f of size 107
polish_clusters: 16:00:05 Polishing cluster e4bee383-39e1-494d-968e-ed129b7c4fc5 of size 147
polish_clusters: 16:00:06 Polishing cluster 0523fa67-f3a0-4343-8ecc-6cb957f5c26c of size 188
polish_clusters: 16:00:07 Polishing cluster cdbe623e-17c5-431a-93ea-a79e978eb475 of size 2260
polish_clusters: 16:00:20 Polishing cluster 6b535889-7107-48c3-9eab-5cb0aa6d1092 of size 258
polish_clusters: 16:00:22 Polishing cluster ca60e86e-f2cc-4ab8-ad13-d8727c344461 of size 202
polish_clusters: 16:00:23 Polishing cluster 70ed3672-75d2-4580-b9a8-8c0d79491f98 of size 306
polish_clusters: 16:00:24 Polishing cluster 53d2a843-bff9-4258-8b8b-701c4d47cd46 of size 61
polish_clusters: 16:00:24 Polishing cluster c40639a3-c3bb-4fec-8662-0e963f47d6db of size 99
polish_clusters: 16:00:25 Polishing cluster b788ec37-d32d-4f0a-baa8-5d3ec18af775 of size 130
polish_clusters: 16:00:25 Failed running command: racon -t 24 -q -1 /tmp/pinfish_b788ec37-d32d-4f0a-baa8-5d3ec18af 775_916745013/reads.fq /tmp/pinfish_b788ec37-d32d-4f0a-baa8-5d3ec18af775_916745013/alignments.sam /tmp/pinfish_b788 ec37-d32d-4f0a-baa8-5d3ec18af775_916745013/reference.fq > /tmp/pinfish_b788ec37-d32d-4f0a-baa8-5d3ec18af775_9167450 13/consensus.fq - exit status 134

And when I type only specific command that doesn´t work:
racon -t 24 -q -1 /tmp/pinfish_30b0c438-8629-4a99-bc51-d09beba70aaf_205375420/reads.fq /tmp/pinfish_30b0c438-8629-4a99-bc51-d09beba70aaf_205375420/alignments.sam /tmp/pinfish_30b0c438-8629-4a99-bc51-d09beba70aaf_205375420/reference.fq > /tmp/pinfish_30b0c438-8629-4a99-bc51-d09beba70aaf_205375420/consensus.fq
terminate called after throwing an instance of 'std::invalid_argument'
what(): [bioparser::FastqParser] error: invalid file format!
Aborted (core dumped)

Few lines from input/ output files:
Pool4_merged_trimmed_BC_raw_transcripts_clusters.tsv
Read Cluster
1b27018c-7eb5-4359-8a0f-95d7265a1c28 640b1d2d-8a92-46a8-ac64-03fec213591b
135a6032-2c24-4f62-9948-8edae6dbd8a4 640b1d2d-8a92-46a8-ac64-03fec213591b
b1faf377-9151-48c0-9dd4-c8d8900117ba 640b1d2d-8a92-46a8-ac64-03fec213591b
5b6b8a04-bf6d-4e32-b3fa-728e582569f9 640b1d2d-8a92-46a8-ac64-03fec213591b
7046ff83-4301-4694-80a1-4d5d8596a371 640b1d2d-8a92-46a8-ac64-03fec213591b
3e1928ba-06cf-4c04-9cf3-8510bcc318d2 640b1d2d-8a92-46a8-ac64-03fec213591b
a2c4f0b8-f6ff-4fa0-9a04-9147bbcbf2ac 640b1d2d-8a92-46a8-ac64-03fec213591b
dea24b20-4eb7-478a-97df-4052a7ab435c 640b1d2d-8a92-46a8-ac64-03fec213591b
1e0226c9-2774-4475-b679-100dc3c45f65 640b1d2d-8a92-46a8-ac64-03fec213591b

Pool4_merged_trimmed_BC.bam
(pinfish) martin.tesicky@turbacz:~/Medaka_parrots/Pool4/pinfish$ samtools view Pool4_merged_trimmed_BC.bam | head -n 5
14a0e3a4-795f-4986-9975-0547ff81815d 0 ENSMUNG00000000050|ENSMUNG00000000050.1|testis 587 60 41S54M2I70M1D29M34S 0 0 GGGGACGCCGGGGCCAAGCGGTAGCAGTGCCATGAGCTGCGAGACTCTGACACGTCTCTGGGACCTGCAATGACAAGTCAGAACAGTAGCCATGCAGAGAGAAAACTGGTGAAATGTCACCAAAGCAGTCAACACCAAAAGTGCAGGTCCAGCAGTCTGTCTCCCGAAAACCATCACTATTCATTTCTCTGCATTTTGTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA D:/.;=>;;&(2+---$''%)(%%&$9@/9=100%(**)))$3,5/..,0+)&693?3;=<96231/4?=E=.)BA=4+#$(/2:;9''+))#4%21>922'7-$83''()##569&888%@538%>>IC72GA99=4--<>&$$$37.)+**?>80)'1/:9418,-1745=BKMFF>A?7>?;961,)A9E?766555556566766789::;===?@> NM:i:7 ms:i:134 AS:i:134 nn:i:0 ts:A:+ tp:A:P cm:i:28 s1:i:127 s2:i:0 de:f:0.0387 rl:i:33
c9c5990c-ad71-4ee1-a7d6-0fe05e9a2947 0 ENSMUNG00000000050|ENSMUNG00000000050.1|testis 587 60 44S54M2D30M1I7M1D8M1D19M2D38M1D5M1I4M1I2M1I85M1D8M2I10M1D10M1I18M3I25M1D34M3I89M2I98M1D15M2I5M3I7M1I36M1I24M1D90M1D61M1D7M2D42M4D35M1D14M1I29M1I25M1I17M2I12M6I8M1I39M1D22M3D19M1D69M1I11M1D51M1D3M1I3M1I1M1I13M1D18M2D19M1I14M2D22M3D1M1I25M2D6M2D9M4I3M1D11M1D3M2I2M1I14M1I38M2D51M1D27M1I2M1I5M1D31M4D34M5D26M1I35M1I25M1D5M1D27M1D22M2D23M6D15M1D7M1D22M2D56M1D20M2D5M1I3M2D39M1I28M1I10M1D21M3I1M1D20M1D2M1D7M1I33M1I14M1D5M1D44M1I5M1D11M1I3M1D3M1D21M1I107M1S * 0 0 GGGGGACGCCGAGACCTGACAGGCAGTGCCATGAGCTGCAGGTAAGACTCTGACACGTCTCTGGGACCTGCAATGACAAGTCAGAACAGTAGCCATGCAGAAAACTGGTGAAATGTCCTCAAAGCAGTCCAGCACCAAAGTGCAGTCCGGCGATCTGTCTCCCGAAACCATCACTATTCATTTCTCTGCATTTGGGAAGGAGAAGAGAGGGAGAGGGAAGAAGAGTTTAAGGAATTCCTTGATGAGGAACTAGATGACCAAAGCATTGTAACAGCACTTGAAATAAAGGAAGACCTCTGCTTGAGCATGCACTGGCCATGGTACTCTGGTCCCAGCTACCTCGCTTAACATAATGGCCAACTCTGCATCACTACTGTCTCATCACCTGCAGTTCTGCCAACTGCAGAGACTACAATAAACCTGTTGGATTCTCCTTCCACATCCCAAGTATTCAGTGCAGTGCCACTAGTCCTGTCTCCTTCATCACACTCATGTAATACAGTTGTAGCTCATCAGGTGCACCACCTGTGAGTCAGAAATCCAGCCTGTCATCCTCCCCATCCTCATCCCCTTCCAGATCAGTTGTCTGCTCTAGTGGATCATCACAGTTTCTAGTTCAGAAAACTTATTTTTAAGGGGTTTAGTCAAGTCCCTTTCAGCAGATGTGGAACCAAAAAGAACCCACCCCACCGATGAGCGCAGACAGCTAGTGAAAACCTTAGTGAAATCTCTGTCTACAGACACTTCCAAACAAGAATCTGAAACTGTGTCTTACGGGCCACCTGACCCAAACTGAACTTGCATCTGTTCAAACAGTTCACTCAACCTCGAGCTACAGGTGGTGATTCAAAACTGCCCTCGTCTCCATTAACATCTCCCTCTGACACCCGTTCCTTTAAGTACCTGAAATGGAGGCTAAAATTGAAGATACTAAAGACGCCTTTCTGGAAGTAATCTGTGAGCCTTTCCAGCTGCTCCAGTAAAATAATGGGTGATGAAAGTGACCAGCCACAGACCCAAAGAGCCTTATCTTCAGGGAGAAGTGCTTCCAGAACTCTCAAACCTTTCCAGTTTGAATGGCCATTTTGAAGCAATAACAACTACAGCATTGAAGAAGAATGTGATTCAGAGAGGACTTCTATGGAAGTGACTCCAACCTGAGCAAGAACGATCAGTCAAAAGTGGCTGAGGAGCATACAAAAAGAGACAGGGCCCAAAGCTCTCAGTCTGCAAGCACAAAGGACGTGAGTTCCAAAACGTCCTCATTAGCGAGGAAAAATGTTCGTGTCTGCATTAGCAAGCAGAGGATGAGGAGTTTTGTGGAACTTTATTCTGAACTTTTCCTTGCTGGAGGATGACTAAAACTGATAAACCTGCTGAAACTTCATGATCGAGATCACCAAAGGAGAAAATGGTACTGGCACTCCAGTAGTGGAGATGAAAAATAATTCCTATGAGCAACAGCCTAAAATACCAGTGAGCTTTATGCTTCTTAACGCTGTTAGTCTATGCTTACCTTAATATCCCTCTCCTAGCTACCAAAGTGGACTTTTATTTAGGAAATGGCCTTGGATTTATGATAGCTGTCTGTGTGATTTAATAACCTCACGTACTCATGAATATCTCAAATTAAAGTGTGAAAAAGCAATGGAATACAGGGAGCTCTAGACATCAAAGAACCTGAAATACTGAAGGGGATGGATGAATGAAATCTATAACACGATCAGAAACATACCATGCTACATTGACTCCTCTGTCTATGTGCGACTTGAAAAGCACCTTACGACTTTCAAAACAAAATATCTCTAGAAGAATATCACAATGAGCCAAAGCCTGAAGTCATATGTCAGCCAGAAAATCTATGGACTTACAGAGCAAAAGATTTCCCTGGTTCCTAAAGTCTGGCACGAAAACGGTTGGAGATAAAGTACCCTATTTGCATTGAACTCGCTAAACAGGATGACTTTTATGGCTAAGGCCCAGGCTGATAAAGAAGAATGCAGAGAAAAGTTATCTGCGGAAAAAAACGAGACGTGAGCAACGAAGAATCAGAAATCTCCAGGGTGGAGCAAAGTACACTAGCCAAAAGGATCCCAGTGCTTTATCTTTTGGAGGACCGGTAGGGAGAAGGAGGAATGGTTCAGAAGGTTTCTTCTCCGCATCAAGCTGAAGTCCTGAGCAAGAAGCTATCCAGTCTATGTGGGGAACAAGCCAGGGATCTTGCCAACACAGAGTAGAGCCGATAGTCAATCTGGAGTTCTCACACACAGCCGAAGCAGCAGCAAGGGAAGTGCAGAAGAGATTGCATCC 8+414)&&'''/)-)$&%%%6>8;=D/5@4(($&"#%$#285D:4992=70335496A>D=)M<FHIABKE9=;=3/7?FEF=9:18:'>>BDE;A=@653,31=>3-13+-23:-4350('+)$$?=&(-(29802H7.1+((8&336>:BA<8=A(33'#,168>/1/:>E?F8<JFF-CG4?=>>?3)/:4@=421/80(,$//5.(%0')-1(::/CBL=:;63);(A-6/197<;<7;0?<4//H48=<@k9<7=>=:,/;5992//)),++(&&00&4,14;5>928''&'','&''$$"(<=A6CB>64&%#"&'.30154.454(**2%$'.-$#$#$%-%%42??G=+).BGC-3B>4-38G@@:=<9358@D<9,354A26;@;BA+&--'((%(0612:8;=>03.;<68-.1671-9G<=ID<1-.-@@>9?3-1>&,,-:>(767A;;>:I7D@B/<;67&)%6C8$$#$#%'14:670-3/-B<'9**''#&02')(('$%$$%"&)(/4++92$+7,:<9++1507;7>//26-:&&;;-,<2:)%($A8DAB=<7;7&);(.($48:<A.+1%()1)@b96>>41(('$'),-.99@=B5EMF/,(@=13:;D1(5<7&%/4>G89,2N95(4==>=+''9768=;<:C58EBEC83:=;><43D'&%'9A;C716<8?:9;/46<;8FDD1'/)'8;:>1BA61:;AD.:2$+CJ:9<*-.BF?>;-/32,AC110;5((#30;?8))9>%%(#'16;D<8/..((E?ABBGFI5/3%&/11=D:1+'+(/>I/A4&$.76<878/%1.;=?83;)D7,124=>=?@;<4=B)9111'''3$$%'6'94,,4$5//,,,(+,GH>E59>0,65.%%$#+637&@C=:295A/FPJ30'&&&)2/CLKF?8@@A+B@>BGI7/)('(?58>(:?$8>>7=79;:5$#(63/5=7/'%)(&&/),)3??=168899+-&).3?>,@C188=512>&;5=7241*?-(4GPE?8.A>802827((&)+$$DQLA=97)43)/(&&++1.,%'()5$.,:80.+0,12<=;:?E@/-53,,/;+5A23966%%.+<((&$),&&-0FE@6@=I8>$39;=D@:<>3-->:'18956=223$&#:+@c7+$$--10KRGBB?6-28B<ERVC)1-+48=6-<>,0/2##6>I?</03AII?B@@<31-.8701,.$&+/4'-67?541,,($.(08@511/+))2/.+;1.+,3>O87A9<2.)-+$&'&46<<;33.,6956?CA?21#1?:D1026E.'AB>5#$-())+132657=0-:34:4ABFF>&)?=&&%'75:+*04)'&&+)%D:8B9-9612=CHD?;@d89@;$$$1$*.994=::9??83).>//.(*%&%$'(()))%%45++@+BA56'(&;DBDB@A5;<85602$##.)),.::?<992:A=D8JCA>4.-<,245;<9B7;>BC::=E<9<558FK@??E8<>;,/7=940/4=??=B>=255&$'=6::0$)+,1&&663**:794-+,,-1/>:13,-1@>/11>K@;>1$TUN?=BDAADK>93+)$621A@@m?2.1)0//;FE66'>>C;>Q::BD;2,=.IE::%%%)..,-/2;<685236;6;5->9%1@67=$@6:1.?:6/)9>4)/3<8?@);3ANAA<=;9((-1+/3=>B@</@ux.>?-:BF?CI@9B?96<)+8;85+-)D''';1=6.B7>E6-&)&98C<3:AD:C@?@;A##$%%.=D8&+,0--/''C><>?9;BC../:&$%3G@.:>2E<>8?=A3611D>B6<:7)<89:''.62,%&&'5R=<F@(($,@6<B482145415,+'234:9:,.--8:.05<KC@941/32?8==-&E<=A NM:i:217 ms:i:1655 AS:i:1655 nn:i:0 ts:A:+ tp:A:P cm:i:322 s1:i:1541 s2:i:0 de:f:0.0718 rl:i:0
4caf762c-9527-47b6-aaea-5c0d324eda2f 0 ENSMUNG00000000050|ENSMUNG00000000050.1|testis 587 41 19S27M1I8M1D19M1D37M1I63M27S * 0 0 GAAGTACCATGAAGCTCAGAGACTCTGACACGTCTCTGAGACCTTCTAATGACAATCAGAACGGTAGCCATGCAAGAAGCTTGGTGAAATAATCTCAAAGCAGTCAGCACCAAAAAGTGCAGGTCCAGCGATCTGTCTCCCGAGAAACCATCACTATTCATTTCTCTGCATTTGGAAAAAAAAAAAAAAAAAAAAAAAAAAA 9-C52=3+++)%((($%%',5;64&++.2$$783&($+52)%)%&.,217;<&&>4DC@2288C9<@<41//#$'$#%'897:2@+$$$$.;><+(%%%*>9$.0%9IC,45/7502>;**I@583-.((77B2>52%&&-(9>B@E@;2522;IGD4<5/':=A@<45+@@877655555667889987766777 NM:i:14 ms:i:112 AS:i:112 nn:i:0 ts:A:+ tp:A:P cm:i:16 s1:i:73 s2:i:0 de:f:0.0886 rl:i:28

The output: Pool4_merged_t_rimmed_BCconsensus_transcripts.fas:

02e3c0c0-b1b5-4f5f-8bf5-05f83f97fbd3|330
TTTTTTTTTTTTTCACAGTTAACAAATATTCTTTATTGTCAGGTCTCAAGACATTATCATAATGGACATTTTTGGACTGTATAAAAACTACTTTTAACTC
AGTGTAAAAGCTCCGTTGAATGTATGAATGATAGCTTAAGAAAGTTTAGAGTAGCAGTTATGGAATTCATTCACTTATTTATGAATAAGGTATAACAGGT
ACCATTCATGCTTTGATCCAAGAGCATTTACAGCTTTGTTTTTGACACTGGTTGTGCCTACAGCTTCTGTATCAGAATTGCAGAAGCACCTCCTCCACTC
CATTGCAAATTCCTGCAAGGCCGTATTGTCCTTGTTTCAATGCATGGGCCATGTGAACAACGATTCTGGCTCCAGACATTCCTATAGGATGTCCAAGAGA
GACACACCTCCATTCATGTTTACTTTTTGTGGATCAATACC
c7a0033e-8bd3-4ea8-8539-8cfe406f915f|85
TTTTTTTTTTTTTTCAAGAACAACTGTTCTTTATTTTATTGACTGGTTGAAGCAGGACTATAAGCCAGGTATATTTCAATCAAGTGTTGGTCCACTCTTA
CCATCAAAAAGAATTTTTTTTTTTTTTTATAATAACATCAACACAAATGGAAGGAATATAAAGCGTCATAATAGGAACTTTCAACTGTACATGATATGAG
ACCATGATCAGACTGGTGCTACTTCAGTATTTATAGACTCTCCACTGTACAGTCCAGCCACACTAGTGTTATTTACCTCCAATCATTCAAGTTCTAGGTA
AAGGATCCTTCTGACTACAGCTCACATCTGAGCCACCAACATGAAATCAAAATGCCATTTGTGCCACTAGCATTGTAGTCTTGTAGAAATATTTCTATAT
TTAGCATATTACTAAAGAATAATTACTATCCTCTCTGAAGTTACATATAGCCATTATAAATATTTACATCAAACATTTACAACTGGTTCATAATATACAA
CACAAGAATTTAGCTATAGTTTCTAATCTTCCAGTGTAAAAGTTTCAAACAACATGTTGCTATCATAATTTCATCTGGTTTGCACACAGTCACAGGCAGT
ACAGGGTATTTCAAAAACTCATGTCACATAAAAAAAAAGGAATGATGTTACTTTAATAACAATTACCTTGGGGATTGATTGTTGTTGGTTTTTGTTGGGG
TTTTTAACAAGCAGTTTTCAATTTCTAAACCCCATCTGATGCTACTACTGACATTTAAAATAAGCTTAAGAGGGAAAAAAATACTTAAAAATAAATACAC
CTTTAAAAAATTCCACAATTAACCATGTCAGAATATTTGTTTTCCAGACAGCTGAAAGGAGACCTTACTCTTCATCATTTCCTTGCACTGAAACAGAGTG
CAGTTCAATCCATTCTTATCTTCTGATTTGTCATCCTATAAATAATGCTGTCGTAGCCAGGATCCATGTTCCAGAGGTTGTAGGAGATAACTATCACAGC
TAAAGCAAGACCTATCATCATCCACAAAATAATGTTGAAGATTACAGAGTAGTTGTAGTTATATGGGTAGGCAAGGTTATATGGATTGTCTGATTCACTC
TGTGAGATTGGAGAATGAGCGAGTCTTCCTTATGTTGGGAGAAATAAACGCCTTTACAGCTACCACTTCTACTACTGCATTCCCACTATACAGATTAAAC
ATCTCATCTGCAAACTTTTGCAAAGAGTCTACAAAATTTGAGAAGCATCCTTGAACTGCTGAGAGTCTTCCCCATATCGTTTTCCAACCTCTTCCAAACC
AGACAGTTCAGAGAATACAGGTCTGGAGAGTGATCTTTGGCTAAGTGCTTGTGTCGAGACAGCAGGCTTGCAATATCATGTAGGACTTGTAGTTCTGACA
GAAAAAGCAAGTCAACCTCATTGTTTCTGCTGAGGGAGTTGAGAGGAAGGGAGCCAAGAATAGAGTTGTCCTGGAATAAGCGGTTTCGCAGTTGGCGCAG
TGTGACAGACAGATCTTCAAATACAGAGTTTGCCTTACCCACCATGTATACCCTTTCCTCACTGGGGGCCAGCTGCAAGACCACAGGAGTCTCCTCAGAG
AACAAAGTATGAATAGCATTTGCAACACTGTCAAGACTGAAAGGAACAGCATTCTCAATAGGGTAAGAAACCCCTTTCACAGGCAGTGCCAGCTTGTCCA
CTCCCTTCACAGTTACCAGCACAGTAGCTCGTGGTCTGTGAAACAGATCACCCACTGCAAGGCCAGGCCAGGAAAGGTCCTCTTCAACAGAAAAGCCCAT
AGACAATGCAGCTACATCTGGGATCCGCTCACCAGGAATGGGCCAACTTCCATCTCGAAAAACAACTGACTGAGGTGATCGTAAGACACTAAATTCATCT
CCACTTACACTGGCAAGACAAGCCGATGTAACCAGCACCGCCACCTCCAGGGACCAGAGCACCCCGCCACGGCACCCCATGTCCGCCGCAGTCCCGGACA
CCGCCGCGCTAAGAGACGCCGCTGGGAAGACGCCGGGCCGCACCGTCAGACCGAGACCACC

I would be very grateful for any help.

**Comment by bsipos** [comment]
Could you please rename the input file for racon to .fastq and see if it still fails?

**Comment by MartinTes** [comment]
I have just renamed input .bam file to .fastq file and it is getting the same error.

**Comment by bsipos** [comment]
Oh, I meant to rename the .fq file to .fastq

**Comment by MartinTes** [comment]
Thank you for your quick response. I am running pinfish by the series of command from the manual here: https://github.com/nanoporetech/pinfish but I am afraid that I still don´t understand where I should rename input files with these extensions.

**Comment by bsipos** [comment]
Nevermind, the issue might be somewhere else. Could you please paste here the contents of /tmp/pinfish_30b0c438-8629-4a99-bc51-d09beba70aaf_205375420/consensus.fq

**Comment by MartinTes** [comment]
I have just checked it and consensus.fq file is empty.

**Comment by bsipos** [comment]
What about these two: /tmp/pinfish_30b0c438-8629-4a99-bc51-d09beba70aaf_205375420/reads.fq /tmp/pinfish_30b0c438-8629-4a99-bc51-d09beba70aaf_205375420/alignments.sam

**Comment by MartinTes** [comment]
I am sending them in the attachment. Reference.fq is also almost empty.
[pinfish_2020_01_09_MT.zip](https://github.com/nanoporetech/pinfish/files/4039882/pinfish_2020_01_09_MT.zip)

**Comment by bsipos** [comment]
Did you align the reads given to spliced_bam2gff yourself? The issue is most likely is that you did not filter out the secondary alignments.
In general, I would advise against using the pinfish tools by themselves, using the [snakemake pipeline](https://github.com/nanoporetech/pipeline-pinfish-analysis) is easier and it takes care of the corner cases.

**Comment by MartinTes** [comment]
Yes, you were right. The issue was I didn't filter out the secondary alignment. When I used the flag  -N 5 --secondary=no in Minimap2 it started to work? Thank you very much for your help!
