### ISSUE TITLE
polish result seems quite strange

### ISSUE THREAD

**Issue by ljw90607** [nanoporetech/pinfish#19]
Dear @bsipos 

I have run the polish_cluster and collapse_partials with the clustered reads and observed somewhat unexpected results.
In my understanding, the polish_cluster is intended to fix only the clustered reads.
But I found that there were more reads in the polish_cluster result than the cluster_gff result. 
I found this quite strange and only difference I made for the run was the input bam file  which is the bam file for gff generation, but only the primary reads were extracted  (polish step did not work with the whole sorted bam file)

I ran the collapse step as well, but didn't seem like it has been polished. 
If you could give me any comment on this issue, I would really appreciate it.

Jungwoo

**Comment by bsipos** [comment]
Did you use the snakemake pipeline or run the tools manually? You are not sure you did not mix up the output files?

**Comment by ljw90607** [comment]
Dear @bsipos 

I have run the tool manually. Could this be due to non-matching data between bam and clustered gff file?

**Comment by bsipos** [comment]
Well, hard to say - but I recommend to use the pipeline and avoid manual runs!

**Comment by ljw90607** [comment]
Thank you I will try the run again and share the result.

Jungwoo
