### ISSUE TITLE
quality assessment of polished data

### ISSUE THREAD

**Issue by MartinTes** [nanoporetech/pinfish#20]
Hi @bsipos,

I have just polished my data with polished cluster and I would like to check their quality, e.g. the percentage of error and Q score. However, I have six different species and only for one, the genome is available.  For one species with a sequenced genome, I used assess_assembly script from Pomoxis and a similar task is also performed by Quast, but both these tools require to have reference genome and they are primarily designed for genomic data. Is there any way how to calculate the error rate without reference available from transcriptomic data?

I would be very grateful for any recommendations.

**Comment by bsipos** [comment]
I am afraid there is no way to calculate the error rate without a reference.
