### ISSUE TITLE
Error racon - exit status 134

### ISSUE THREAD

**Issue by guosongjia** [nanoporetech/pinfish#23]
Dear all
Following the README file, I finished the `spliced_bam2gff` step and `cluster_gff` step. Now I want to use `polish_clusters` software to polish the transcript based on "clusters.tsv". The following error occurred.
 ```
$  polish_clusters -a clusters.tsv -t 12 -c 50 -o octosporus_diploid_19H.full_length.consensus_transcript.fas ../octosporus_diploid_19H.full_length.sorted.bam
polish_clusters: 13:04:48 Polishing cluster 1e6f6eaa-e7c2-4c42-bb3a-1124cff9cd21 of size 276
polish_clusters: 13:04:49 Polishing cluster e24f0d1f-8273-41e6-be26-64163d420938 of size 103
polish_clusters: 13:04:49 Polishing cluster 72f6a514-7c31-4cf4-bd8b-3751fe7a95b7 of size 71
polish_clusters: 13:04:49 Polishing cluster 0a5a9eba-24c2-40c6-a2e8-8abea6f4c504 of size 4967
polish_clusters: 13:05:21 Polishing cluster ec124557-145e-4796-875b-a11c9bfe19b0 of size 7196
polish_clusters: 13:05:22 Failed running command: racon -t 12 -q -1  /tmp/pinfish_ec124557-145e-4796-875b-a11c9bfe19b0_838333432/reads.fq /tmp/pinfish_ec124557-145e-4796-875b-a11c9bfe19b0_838333432/alignments.sam /tmp/pinfish_ec124557-145e-4796-875b-a11c9bfe19b0_838333432/reference.fq > /tmp/pinfish_ec124557-145e-4796-875b-a11c9bfe19b0_838333432/consensus.fq - exit status 134
```
Can anyone help me to solve this error?
Thanks~
Guo-Song

**Comment by bsipos** [comment]
Racon can have issues on certain processor architectures when installed from bioconda. Please compile racon from source and try again.

**Comment by guosongjia** [comment]
> Racon can have issues on certain processor architectures when installed from bioconda. Please compile racon from source and try again.

Thanks for your advice!
I found that my alignment `bam` file contained secondary alignment and supplementary alignment. So, I set extra parameters `--secondary=no` and `-Y` during `minimap2` reads mapping.
Now, it works well.
Thanks~
Guo-Song
