### ISSUE TITLE
the same full length sequences but in different order results different result

### ISSUE THREAD

**Issue by Pai-Shenglei** [nanoporetech/pinfish#24]
Hi,
    I have a fasta file that contains some full length sequences.When I adjusted the order of full sequences in the file. I got the different clusters.tsv file.The command line as follow:
spliced_bam2gff -s -M CON1.sorted.bam > CON1.raw_transcripts.gff
cluster_gff -c 10 -a CON1.clusters.tsv CON1.raw_transcripts.gff > CON1.clustered_transcripts.gff

I don't know why and I need your help.Could you help me?
If you need my test file, I can provide.

**Comment by bsipos** [comment]
Did you sort the BAM file? If you did not then this behaviour is expected. Also, the results will be wrong.

**Comment by Pai-Shenglei** [comment]
Yes, I sorted the BAM file.

**Comment by bsipos** [comment]
If you sort the BAM file, then the GFF records will always be in the same order, hence the output should be the same. Please use the snakemake pipeline to avoid potential glitches.
