### ISSUE TITLE
error loading or unzipping Reference Data

### ISSUE THREAD

**Issue by AndrewWT** [nanoporetech/pinfish#6]
Hello, I am getting the error below when I execute snakemake.  I have followed the tutorial instructions here: https://community.nanoporetech.com/knowledge/bioinformatics/using-pinfish-for-gene-tra/tutorial   

I build the proper environment and get the tutorial to run but when I use my own data in the RawData and ReferenceData folders after updating the config.yaml file I am getting:

(Pinfish) -bash-4.2$ snakemake -j 1
Building DAG of jobs...
InputFunctionException in line 73 of /mnt/home/thom1524/Pinfish/Snakefile:
KeyError: 'AMC_annotation.gff.gz'
Wildcards:
unzipFile=AMC_annotation.gff.gz

It seems to me that the data I give it are not being opened or read.  Any help would be much appreciated!

**Comment by bsipos** [comment]
Hello,

This is not a pinfish issue. Please submit an issue to the tutorial repository.

Botond
