### ISSUE TITLE
error from spliced_bam2gff

### ISSUE THREAD

**Issue by yuntwang** [nanoporetech/pinfish#7]
Hi
when I use the command:
./spliced_bam2gff -s  -t 10 -M data.sorted.bam >data.raw_transcripts.gff
I get an error:
**panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x4cd426]

goroutine 1 [running]:
main.SplicedBam2GFF(0x7fff21087b9a, 0x57, 0x52a9e0, 0xc420108008, 0xa, 0xc420108001, 0x2)
	/home/OXFORDNANOLABS/bsipos/gt/pinfish/spliced_bam2gff/bam2gff.go:29 +0xa6
main.main()
	/home/OXFORDNANOLABS/bsipos/gt/pinfish/spliced_bam2gff/main.go:22 +0x146**
why?
Hope to get your reply!
Thanks

**Comment by bsipos** [comment]
Is the BAM file big? Is the data sensitive? If not, it would be useful if you could upload it somewhere and give access to it.

**Comment by yuntwang** [comment]
@bsipos 
I have found the reason that the header of bam is error.
