### ISSUE TITLE
error from polish_clusters

### ISSUE THREAD

**Issue by yuntwang** [nanoporetech/pinfish#8]
Hi,
I use the polish_clusters to correct my nanopore data and hope to get the consensus fasta,
and I encounter an error.
My command line:
/polish_clusters -a data.clusters.tsv -o data.consensus.fasta -t 10 -c 5 -d ./data/temp data.sorted.bam
why?
Hope to get your reply.
Thanks

**Comment by bsipos** [comment]
What was the error exactly?

**Comment by yuntwang** [comment]
@bsipos  I am sorry
The error like this:
polish_clusters: 15:43:24 Failed running command: samtools view -h - exit status 1
but the samtools exists:
**samtools** 

Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.18 (r982:295)

Usage:   samtools <command> [options]

Command: view        SAM<->BAM conversion
         sort        sort alignment file
         mpileup     multi-way pileup
         depth       compute the depth
         faidx       index/extract FASTA
         tview       text alignment viewer
         index       index alignment
         idxstats    BAM index stats (r595 or later)
         fixmate     fix mate information
         flagstat    simple stats
         calmd       recalculate MD/NM tags and '=' bases
         merge       merge sorted alignments
         rmdup       remove PCR duplicates
         reheader    replace BAM header
         cat         concatenate BAMs
         targetcut   cut fosmid regions (for fosmid pool only)
         phase       phase heterozygotes

**Comment by bsipos** [comment]
It seems your samtools is very old. Could you please install the lates version from bioconda and try again.

**Comment by yuntwang** [comment]
Thanks
